#!/bin/sh
#
# Maildir shell script:
# make a Maildir directory and subdirectories.
#
# Syntax:
#
#     maildir-mkdirs [path]
#
# This script makes the required directories:
#
#    * `cur` for current mail
#    * `new` for new mail
#    * `tmp` for temporary files
#
# This script also makes the popular diectories for IMAP and POP:
#
#    * `.Drafts` for work in progress mail
#    * `.Sent` for sent mail
#    * `.Templates` for mail templates
#    * `.Trash` for deleted mail
#
# The result:
#
#     Maildir/cur
#     Maildir/new
#     Maildir/tmp
#     Maildir/.Drafts
#     Maildir/.Sent 
#     Maildir/.Templates
#     Maildir/.Trash
#
# ## Path details
#
# The path default is the current user's home directory.
#
# The path must exist.
#
# ## Examples
#
# To make directories in the current user's home directory:
#
#     maildir-mkdir
#
# To make directories in a specific directory:
#
#     maildir-mkdir /home/alice
#
# To make directories that get automatically copied when a
# typical Linux sysadmin creates a new user on the system:
#
#     maildir-mkdir /etc/skel
#
# Program: maildir-mkdirs
# Version: 1.2.0
# Created: 2010-10-16
# Updated: 2017-03-31XS
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
path=${1:-$HOME}
cd "$path"
mkdir -p Maildir/{cur,new,tmp,.Drafts,.Sent,.Templates,.Trash}
